### ISSUE TITLE
TMN lost settings and options... again!

### ISSUE THREAD

**Issue by PSIG-dev** [vtoubiana/TrackMeNot#125]
Hello!  Thanks for your efforts with TMN!  This is the second time TMN has lost all settings and options in the last year.  Before I uninstall and reinstall to set it up again, is there a file that holds this info that I can access to copy the custom info or restore it?

A screenshot is attached to show the effect - no default search engines or settings, and no custom stuff I've done (RSS feeds, search engines, timing, keywords, etc).  Thanks!

![TMN_lobotomized](https://user-images.githubusercontent.com/36828017/68077850-89282580-fd88-11e9-8930-6a66c629eaeb.jpg)

**Comment by redst4r** [comment]
same problem here. Not sure if this is related, but opening the `Options`, I get a 
```
Error handling response: TypeError: options.feedList.join is not a function
    at TMNSetOptionsMenu (chrome-extension://cgllkjmdafllcidaehjejjhpfkmanmka/option-script.js:152:37)
    at TMNLoadOptionWindow (chrome-extension://cgllkjmdafllcidaehjejjhpfkmanmka/option-script.js:348:9)
```

**Comment by PSIG-dev** [comment]
Bump for an answer to my one question, please?

**Comment by bloodclot** [comment]
This just happened to me too

Error handling response: TypeError: options.feedList.join is not a function

Stack Trace: 
option-script.js:147 (TMNSetOptionsMenu)
    var feedList = options.feedList.join('|');

option-script.js:337 (TMNLoadOptionWindow)
        TMNSetOptionsMenu(items["options_tmn"]);
